<?xml version="1.0" encoding="utf-8"?><Database Name="hospital-db" Class="HospitalProjectDbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=HAWX-NOTEPC\SQLEXPRESS;Initial Catalog=hospital-db;Integrated Security=True;Pooling=False" SettingsObjectName="HospitalMvcApplication.Model.Properties.Settings" SettingsPropertyName="hospital_dbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Role" Member="Roles">
    <Type Name="Role">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Role_UserRole" Member="UserRoles" ThisKey="Id" OtherKey="RoleID" Type="UserRole" />
    </Type>
  </Table>
  <Table Name="dbo.UserRole" Member="UserRoles">
    <Type Name="UserRole">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Role_UserRole" Member="Role" ThisKey="RoleID" OtherKey="Id" Type="Role" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="User_UserRole" Member="User" ThisKey="UserID" OtherKey="Id" Type="User" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="User_UserRole" Member="UserRoles" ThisKey="Id" OtherKey="UserID" Type="UserRole" />
    </Type>
  </Table>
</Database>